[test.assertion.1] line 16 assertion My_Storage_Array(2)=2: SUCCESS
VERIFICATION SUCCESSFUL
